apiVersion: v1
kind: Pod
metadata:
  name: myapi
spec:
  containers:
  - name: my-api
    image: mredjem/my-api:0.0.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelay: 5
      timeoutSeconds: 1
      periodSeconds: 10
      failureThresold: 3
    env:
    - name: BIND_HOST
      value: "0.0.0.0"
    - name: BIND_PORT
      value: "8080"
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
