version: '2'
services:
  my-sidecar:
    image: mredjem/my-sidecar:0.0.1
    container_name: my-sidecar
    build: ./my-sidecar
    ports:
      - "443:443"
    depends_on:
      - my-api

  my-api:
    image: mredjem/my-api:0.0.1
    container_name: my-api
    build: ./my-api
    ports:
      - "8080:8080"
    environment:
      - BIND_HOST=0.0.0.0
      - BIND_PORT=8080
