version: '2'
services:
  sidecar:
    image: mredjem/sidecar:latest
    container_name: sidecar
    build:
      context: ./nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    command: [nginx-debug, '-g', 'daemon off;']

  my-api:
    image: mredjem/my-app:latest
    container_name: my-api
    build:
      context: ./my-app
    environment:
      - BIND_HOST=0.0.0.0
      - BIND_PORT=8080
